### ISSUE TITLE
Dutyplan Sammelthread

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#10]
Die Funktionsweise des Dutyplans nicht mir nicht klar.

- Müssen wir wirklich für jede Veranstaltung die benötigten Rollen immer wieder anlegen?
  - Vorschlag: Default Rollen wie Vorführer, Gastro, Kasse by default anlegen.
- Warum haben die Rollen, Felder für "StartZeit" und "EndZeit :)"

- Normale User sollen Rollen nicht editieren dürfen oder gar löschen

- Wie funktioniert die Einschreibung? Und was macht dieser Knopf?
![image](https://user-images.githubusercontent.com/18573108/71181396-5c669980-2274-11ea-9c57-c8c031266485.png)

**Comment by Neolyum** [comment]
[ ] Default Rollen
[ ] Berechtigungen für edit oder Löschen

**Comment by Neolyum** [comment]
dieser Knopf ist die Möglichkeit sich einzuschreiben.
Momentan ist das noch nicht sonderlich intuitiv und wird noch überarbeitet!

**Comment by Oliver3911** [comment]
Was ich ja intuitiver fände, wäre wenn der Knopf ![image](https://user-images.githubusercontent.com/18573108/71254318-d6f1f080-232a-11ea-9540-5ccd32da773f.png) zum anlegen von neun Rollen ist. Und ein klick auf die Rolle führt mich zur einschreibung für diese.
Wie/wo man dann eine Rolle editiert wüsste ich gerade aber nicht ^^

Aber wir schreiben uns halt deutlich mehr in Rollen ein, als sie zu erstellen (gerade wenn sie per default da sind) oder zu bearbeiten. Daher wäre es schön wenn dies möglichst DAU sicher und mit weniger Klicks und auch mobilefreundlich geht (siehe #14 )

Die default rollen wäre übrigens eine mögliche option im config file, aber da bin ich offen wo man das einstellt.

**Comment by COeins** [comment]
Oliver hatte es oben schon geschrieben, aber da es echt nervig ist wiederhole ich das hier nochmal: 
Warum muss ich jedes Mal im Dienstplan die Zeiten mit ausfüllen? Die Zeit ergbit sich doch aus der Veranstaltungszeit (+ein konfigurierbarer "Vorlauf"). Ich würde mir wünschen, dass die Felder da wegkommen. 

(Alternativ wäre vorausgefüllt auch okay, aber dann müssten wir Situationen betrachten, dass jemand die Dienste verschieben muss, wenn sich der Startzeitpunkt einer Veranstaltung ändert oder so. Also am besten ganz weg...)

**Comment by Neolyum** [comment]
Dies ist (wie ihr heute ja gesehen habt :) ) auf development und wird gepusht werden!
Die bessere Intuitivität wird in den nächsten Tagen kommen
- [ ] Done

**Comment by Oliver3911** [comment]
Eintragen scheint in der aktuellen Version nicht zu gehen.

**Comment by Neolyum** [comment]
Hab den Server mal neugestartet, wenn ich in den MovieEvents auf einen Job drücke, trägt es mich ein. Funktioniert es nach dem Neustart auch bei euch?

**Comment by Oliver3911** [comment]
nicht wirklich, ich probiere das nach der arbeit noch mal genauer, aber mit user "bruce" geht es gerade nicht.

**Comment by Oliver3911** [comment]
Ebenfall, es ist schwer sich für jobs ganz rechts einzutragen weil sich das overlay bei 1080p genau über den Link schiebt

![image](https://user-images.githubusercontent.com/18573108/71992455-b0421e00-3235-11ea-9935-f8fcbfd6ba50.png)

**Comment by Neolyum** [comment]
Tatsache. Ich habe einmal den Job "Kasse" im Testfilm toast gelöscht - jetzt kann man sich dort eintragen aber dafür bei Gastro nicht mehr, was vorher ging. Ich hab heute keine Zeit mehr, werde aber morgen einmal Nachschauen, was da schief läuft!

**Comment by Neolyum** [comment]
sollte jetzt funktionieren! wenn noch ein Job fehler wirft, editiert ihn einmal, das sollte ihn reparieren!

**Comment by Oliver3911** [comment]
Ähmm wie war das mit Dutyplan für Sonderveranstaltungen?
Kommt da noch was?

**Comment by Oliver3911** [comment]
Beim Eintragen in der Übersicht in den Dutyplan wird man im anschluss nach MovieEvents weitergeleitet. 
Das ist unschön, gerade wenn man sich für mehre Events eintragen will, was ja eigentlich in der Übersicht passieren sollte.
Ist es möglich dort hin geleitet zu werden wo man herkommt?

**Comment by Oliver3911** [comment]
Klingt man in movieEvents auf ein Rolle für einen Dutyplan wird man sofort eingetragen (ohne Popup). Klickt man erneut wird man ausgetragen, hier kommt allerdings eine Fehler Seite

Dieses Verhalten (ohne die Fehlerseite und Popup) wünsche ich mir in der Übersicht.

**Comment by Neolyum** [comment]
@Oliver3911 mit der Weiterleitung denk ich mir was aus :)
Die Funktionalität für SpecialEvents und für die Übersicht kommt im nächsten merge!
Den Bug, dass man als Admin die Errorpage bekam, hab ich gefixt.

Die MyJobsseite ist iirc @Pollopiccante s Werk :D

**Comment by Neolyum** [comment]
@Pollopiccante wenn das erledigt ist, schließ das mal bitte :)

**Comment by Oliver3911** [comment]
Bitte die default Dutyplan Jobs aus Config-File ladbar machen

**Comment by Neolyum** [comment]
@Oliver3911 Done :)
