### ISSUE TITLE
Strange Placeholder inside login fields

### ISSUE THREAD

**Issue by glombart** [kino-im-kasten/SWT2019#11]
Folgende Platzhalterinfos befinden sich in den Loginfeldern:
??user.login.username_placeholder_en_US??
??user.login.password_placeholder_en_US??
(Siehe Bild)

Tested on Firefox 71 (64 bit) - Ubuntu 19.04

![image](https://user-images.githubusercontent.com/15110541/71181348-3f31cb00-2274-11ea-8c4d-405990d253ad.png)

**Comment by Oliver3911** [comment]
Nicht unter Chrome Version 79.0.3945.79
Aber unter Firefox 68.3.0esr (64-bit)

**Comment by COeins** [comment]
... auch im Firefox 72 unter Windows zu beobachten.
