### ISSUE TITLE
No Javascript Sammelthread

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#13]
Deaktiviert man Javascript scheint alles weiterhin zu gehen. Hier würde ich mal alle sachen sammeln die nicht gehen, vllt bekommt man das ja gelöst.

Wenn nicht würde ich mir einen "Diese Seite benötigt Javascript" Hinweis irgendwo wünschen.

![image](https://user-images.githubusercontent.com/18573108/71241650-6d62e980-230c-11ea-91a3-f943001afc01.png)

**Comment by Oliver3911** [comment]
Benutzer Popup Menu geht nicht 
![image](https://user-images.githubusercontent.com/18573108/71241751-a7cc8680-230c-11ea-8d76-ee86615b1980.png)

**Comment by Oliver3911** [comment]
Side-Menu funktioniert auch nicht. 
Ein-/Ausblenden zB in Mobiler Ansicht nicht möglich

**Comment by Andevour** [comment]
@Oliver3911 hier würde ich gerne paul-mars assigen, aber der ist noch nicht im Repo. Könnt ihr ihn noch einladen?:)

**Comment by Oliver3911** [comment]
@Andevour laut @COeins sind wurde an alle eine Einladung gesendet. Mehr Details stehen im Chat, hab gerade keine Zeit das hierher zu kopieren ^^

**Comment by paul-mars** [comment]
Javascript wird für folgende Dinge benötigt:
* Die Modals (Löschbestätigungen) werden mit js generiert und können von Bootstrap Seite her auch nicht anders als mit js gesteuert werden
* Die Live-Berechnung der Einnahmen während der Ticket-Eingabe
* Einige weitere Bootstrap Features
* (Diagramme welche evtl. auf die Übersichtsseite gekommen wären)
* (Seiten-Menü öffnen und schließen)
* (irgendeine Sache im Distributor)
* (Der zurück Button war mit Javascript geplant)

Wegen der nicht ausgeklammerten Features denke ich, dass unserer Seite nicht für den Javascript freien Betrieb geeignet wäre und daher werde ich mich um die Anzeige eines Textes wie "Diese Seite benötigt Javascript" kümmern.

**Comment by Oliver3911** [comment]
kann ich gut mit leben ^^
diese meldung vllt schon beim login anzeigen bzw spätests dann wenn wirklich js benötigt wird.

werden die libs eigentlich schon local gehostet?

**Comment by paul-mars** [comment]
So viel ich weiß ist das in Arbeit und es sollte eigentlich an allen Stellen schon lokal sein.

**Comment by Oliver3911** [comment]
> @Oliver3911 So viel ich weiß ist das in Arbeit und es sollte eigentlich an allen Stellen schon lokal sein.

Zum Zeitpunkt der Nachricht war das zumindest auf der Live Version noch nicht der fall, jetzt schaut es aber danach aus :+1: :D

**Comment by paul-mars** [comment]
Die Javascript Warnung habe ich jetzt auf meinem Branch hinzugefügt, sie sollte bald auch auf dem Liveserver erscheinen.

**Comment by Oliver3911** [comment]
Die Javascript Warnungen dürfen ruhig schon Rot und nervig sein ^^

**Comment by COeins** [comment]
Die Art wie der Hinweis platziert ist gefällt mir, permanent sichtbar aber trotzdem nicht im Weg. 
Allerdings muss ich Olli zustimmen, er ist noch zu unauffällig. Macht ihn rot oder einen fetten Rahmen drum oder sowas...

**Comment by Oliver3911** [comment]
In der Fassung von Mittwoch war die Meldung ja schön rot, unter der Annahme dass dies bald gemerged wird mache ich das issue mal zu.
