### ISSUE TITLE
Alte Buchungen in neuer Veranstaltung

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#15]
Beim Anlegen einer neuen Veranstaltung werden Buchungen angezeigt die in der Vergangenheit liegen.
Hier braucht es einen Filter der nur aktuelle und in der Zukunft liegende Anzeigt.
Alles was vorbei ist und archiviert ist spammt nur die Liste zu und das wird dann schnell unübersichtlich!

![image](https://user-images.githubusercontent.com/18573108/71245921-06e2c900-2316-11ea-858e-b847c7c17a79.png)

**Comment by Andevour** [comment]
Done.

War im _latest_ build vorhanden, doch noch nicht stable auf master getestet. Sollte nun dazukommen. Es werden die **nicht-archivierten Buchungen** angezeigt. Das ist präventiv, wenn im Nachhinein festgestellt werden sollte, das was fehlte, etc.

**Comment by Oliver3911** [comment]
Der Fehler tritt noch immer auf.
![image](https://user-images.githubusercontent.com/18573108/72331605-c24e1180-36b8-11ea-884d-fe4dba419673.png)

**Comment by Oliver3911** [comment]
> Done.
> 
> War im _latest_ build vorhanden, doch noch nicht stable auf master getestet. Sollte nun dazukommen. Es werden die **nicht-archivierten Buchungen** angezeigt. Das ist präventiv, wenn im Nachhinein festgestellt werden sollte, das was fehlte, etc.

Alles gut ich kann nicht lesen ^^
