### ISSUE TITLE
Dokumentation Sammelthread

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#17]
Viele Dinge sind noch nicht wirklich gut erklärt für neue User.
Wie bereits besprochen wären hier erklärende Texte auf der Seite in Form von einem Fragezeichen/Menüpunkt in der Seitenleiste wo die Anleitung verlinkt wird oder als Mausover über den Objekten oder beides sehr wünschenswert.

Ich sammle hier mal dinge die mir auffallen. Ebenfalls haue ich das auf Hohe Prio, aber wenn es diese Erklärungen erst ganz am Ende gibt ist das okay, aber vermerkt vllt mal was ihr vllt schon vorbereitet habt. 

Danke

**Comment by Oliver3911** [comment]
Erklärung der Farben bei Filme, Veranstaltungen, Buchungen etc.

**Comment by Oliver3911** [comment]
Fehlende Maus-Popup-Overlays #2

**Comment by aendeavor** [comment]
@paul-mars soll hier ein Template generieren für die Dokumentation und es auch schon mit Inhalt anfüttern. Diese Seite soll auch aus dem linken Menu her erreichbar sein.

@Pollopiccante, die stellst dann bitte ein, dass man nach dem ersten LogIn, also nach dem Einsetzten des eigenen Passworts, auf diese Seite geleitet wird.

@Nawatix Du hilfst @paul-mars mit dem Inhalt.

**Comment by paul-mars** [comment]
@Pollopiccante die Seite ist auf development unter `documentation.html` und man wird über den Link in der sidebar auf `.../documentation` weitergeleitet.

Könntest du den Controller dafür gleich noch schreiben wenn du das mit dem ersten login schreibst?

**Comment by Pollopiccante** [comment]
Ist jetzt mit Controller und Weitereitung nach erstem login auf development

**Comment by Nawatix** [comment]
@paul-mars hab jetzt auf development die erklärung der farben aus den übersichten hinzugefügt, könntest du dir das angucken und falls nötig aufhübschen?

**Comment by paul-mars** [comment]
ja werde ich machen

**Comment by Oliver3911** [comment]
"Bauanleitung" für die Sofware bitte auch Dokumentieren
