### ISSUE TITLE
Anmerkungen "Aktuelle Veranstaltungen"

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#19]
_Dies ist ja die Startseite und da wir uns über das Semester primär für den Dienst einschreiben, soll dies so schnell und übersichtlich wie möglich hier passieren._

## Aufgaben

* [x] Nicht abgerechnete Buchungen oben halten und Markieren @Nawatix 
* [x] Prüfen wo noch keine Personen eingeschrieben sind ( + irgendeine aufdringliche Markierung) @Neolyum 
* [x] Eintragen möglichst ein Klick auf eine Rolle (die wie in #10 ja schon bei default angelegt sind) @Neolyum 
* [x] Ticketnummern hinterlegen @Andevour 

---
[DEPRECATED / NOT VIABLE]
* keine Trennung von Film- und Sonderveranstaltungen
  - beide in einer Liste chronologisch
* alle zukünfigen Veranstaltungen hier anzeigen, keine Beschränkung
* eine markierung auf der übersicht ob dies die letzte veranstaltung einer buchung ist wäre schön, damit direkt die abrechnung machen kann

**Comment by Oliver3911** [comment]
Veranstaltungen wo Tickets hinterlegt wurden bzw die Buchung abgerechnet wurde können aus der Ansicht verschwinden

**Comment by Andevour** [comment]
Ist teilweise schon auf _latest_, aber noch nicht komplett.

**Comment by Andevour** [comment]
Trennung der Events hat Hintergrund; in einer Liste ist es absolut unhandlich, zu testen, wann movieEvent und wann specialEvent vorliegt, um dann die Richtigen Eigenschaften abzufragen. Die Trennung bleibt also aufrecht.

**Comment by Andevour** [comment]
Außerdem werden nicht alle zukünftigen Veranstaltungen hier angezeigt. Das führt auf mobilen Endgeräten zu einer inakzeptablen UX. Falls mehr als 15 Filmveranstaltungen existieren, werden nur die ersten 15 angezeigt.

**Comment by Andevour** [comment]
@Oliver3911 ihr sprecht von Buchugen - meint ihr auch die Buchungen oder die Filmveranstaltungen zu den Buchungen? Ich habe mal @Nawatix assigend, weil Buchung dasteht. Andernfalls werden die Filmevents sortiert dargestellt.

Außerdem ist das Darstellen der letzten [Buchung] Filmveranstaltung zu einer Buchung nicht wirklich eine Verbesserung, da ihr euch auch gewünscht habt, dass Events mit eingetragenen Ticketnummern nicht mehr in dieser Liste auftauchen. Daher kann in der Buchung eingesehen werden, ob eine Buchung vollständig ist, und nicht im Event, was das nicht weis. Außerdem sind die Events in den Buchungen nur eine Liste, was besser ist, da man allgemein prüfen muss, ob noch Events offen sind, und nicht nur das letzte.

**Comment by Andevour** [comment]
Das Darstellen von Filmveranstltungen, die noch keine hinterlegten Tickets haben, ist erledigt.

Done. [22.12.19-18:39]

**Comment by Oliver3911** [comment]
@Andevour gemeint hier sind wirklich die nicht Abgerechneten bzw in diesem Fall die **Veranstaltungen** ohne eingetragene Tickets

Ach nett wäre es gewesen wenn in der Übersicht Buchungen zu sehen wäre wo alle Veranstaltungen fertig sind (Zeitlich + Tickets eingetragen), aber die noch nicht abrechnet sind. So das man an die mit einen Klick kommt. Reicht aber auch nicht wenn nicht abgerechnete Buchen unter Buchungen markiert sind. (Kann Kriterium)

**Comment by COeins** [comment]
Nochmal zur Klarstellung: Es soll keine Ansicht geben, in der Buchungen und Events durcheinander angezeigt werden. Das führt nur zu Unübersichtlichkeit. 

Wenn ich mich über Buchungen informieren will, kann ich jederzeit auf die Buchungsseite gehen. 
Bei dargestellten Events wärees schon sinnvoll, wenn das aktuellste immer oben steht, egal ob es sich um Film oder Special handelt. 

Das mit Event so lange in der Liste halten bis die Kartennummern eingetragen wurden halte ich für sehr sinnvoll, da es dem Dienst am Abend eine Menge Klickarbeit abnimmt. Könnte man aber auch einfacher lösen, in dem man das Event immer noch 3 Stunden nach Veranstaltungsende stehen lässt, unabhängig von anderen Parametern.

**Comment by Andevour** [comment]
@Oliver3911 Buchungen können wir da noch hinpacken, das ist kein Problem. Ich have @Nawatix dafür assigned.

@COeins das mit den aktuellten Events ist nach dem neusten Push so - wenn man sich den anmelden könnte, was gerade, aus nicht wirklich erfindlichen Gründen, nicht funktioniert... Wir schauen mal. Eigentlich sollte das Anmelden funktionieren...

**Comment by Oliver3911** [comment]
Die aktuelle Version auf dem Server scheint keine Filmveranstaltungen hier anzuzeigen.
Bitte mal prüfen.
Danke

**Comment by COeins** [comment]
Kann den Fehler bestätigen.

**Comment by Oliver3911** [comment]
Ich hab gerade zum Testen eine bestehende Buchung im Datum ablaufen lassen.
In der Veranstaltung dieser Buchung sind alle Rollen befühlt und Tickets eingetragen
Die Buchung habe ich abgerechnet.

Die Veranstaltung erscheint aber immernoch in der aktuellen Übersicht. Gibt es hier einen Bug oder übersehe ich was?

**Comment by Nawatix** [comment]
Habe mir das auch gerade angeguckt und selbst Veranstaltungen die in der Vergangenheit stattgefunden haben und als Plannungsstatus abgerechnet haben werden bei den aktuellen Veranstaltungen angezeigt. @aendeavor könntest du dir das mal angucken?
