### ISSUE TITLE
Keine Prüfung von doppelten Kartennummern

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#20]

**Comment by COeins** [comment]
Was meinst du damit? Ganz ohne Beschreibung verstehe ich nicht, was du dir darunter vorstellst.

**Comment by aendeavor** [comment]
Das gestaltet sich als schwieriger als gedacht. Die Logik, also was passieren müsste, wäre nicht das Problem, sondern es benutzbar umzusetzen. Ich würde gerne davon absehen.

**Comment by COeins** [comment]
Dann mache ich der Übersichtlichkeit halber hier mal zu...
