### ISSUE TITLE
Api-Dokumentation

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#21]
Ich würde gern damit beginnen, die REST-API zu testen. Dazu wäre es echt hilfreich eine Dokumentation zu haben. (Nichts ausführliches, eine Liste mit den Endpunkten und deren Parametern wäre schon recht hilfreich)
Gibt es so etwas schon?

**Comment by COeins** [comment]
:nerv: 😙

**Comment by COeins** [comment]
Okay, das folgende haben wir gefunden. Der Test beschränkt sich notwendigerweise darauf. Falls es noch mehr zu testen gibt, sagt einfach Bescheid... Ebenso, falls etwas der hier dargestellten Dinge fehlerhaft sein sollte.

/rest/event?id=<ID>
/rest/eventList
/rest/eventsAfter?amount=<NUM>&start=<DATE>
/rest/eventsBetween?start=<DATE>&end=<DATE>
/rest/dutyplan?eventId=<ID>

Ich vermute außerdem, dass alle Endpunkte per GET erreichbar sind.

**Comment by FelixRTU** [comment]
Es ist jetzt möglich die Veranstaltungen eines Nutzer in einem Zeitraum abzurufen

/rest/eventsForUser?uuid=[UUID]&start=[DATE]&end=[DATE]

z.B. 

/rest/eventsForUser?uuid=61cf7ce7-283f-45a4-ae19-52f6a600c5ef&start=2019-12-03T20:15&end=2020-12-03T20:15

**Comment by COeins** [comment]
Nur zum Verständnis - wie komme ich an die UUID? Wird die in der Nutzerverwaltung irgendwo angezeigt?

**Comment by FelixRTU** [comment]
Im Moment ist die nur bei Event-Anfragen unter den Jobs zu finden. Würde euch die die uuid in der Nutzerverwaltung ausreichen oder soll es noch andere Wege geben an diese zu gelangen? Und so wie ich das verstehe, soll dann auch nur ein Admin die uuids einsehen können richtig?

**Comment by Oliver3911** [comment]
Ich denke in der Nutzerverwaltung und nur für die Admins sichtbar klingt gut.
