### ISSUE TITLE
Kein Login Möglich!

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#22]
Nach eingabe der Login Daten
zB Bruce

bekommt man die Error Page

![image](https://user-images.githubusercontent.com/18573108/71351803-eb292e00-2574-11ea-8e55-0cef891e5fcc.png)

**Comment by COeins** [comment]
Eventuell wäre es, gerade jetzt in der Testphase, günstiger die vollen Exceptions zu sehen, statt nur die Zusammenfassung?

**Comment by Neolyum** [comment]
Der Login ist möglich. Was nicht funktioniert ist die Evaluation Specialevent.typeAsString. das heißt seiten, die nichts mit special Events zu tun haben, funktionieren. Ihr könnt also, bis ich mir das Angesehen hab, über die direkt Links (bspw /distributor/ oder /bookings) weitertesten :)

**Comment by Andevour** [comment]
@Neolyum habe dich unassigned, weil ich es nun gefixt habe. Das war ein komische rbug, dessen Ursprung ich slebt nicht kenne, aber ich habe einfach den aktuellsten Stand von master nun gezogen und alles funktioniert wieder schön :D

**Comment by Neolyum** [comment]
wunderbar :D
