### ISSUE TITLE
Platzhalterstrings im Hauptmenu

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#23]
Ähnlich wie #11 aber diesmal im Hauptmenü. (Siehe Screenshot)

Immer noch FF 72, Win 7, System Local EN.US.

(Außerdem sind da noch seltsame Plusse im Hintergrund, wo ich nicht so recht weiß wo die herkommen. (s. rote markierung) Ggf. brauchen die eine eigenes Ticket? )

**Comment by COeins** [comment]
![issue23](https://user-images.githubusercontent.com/1882002/71413469-9c51c600-2652-11ea-8054-98c0abd36abf.jpg)

**Comment by COeins** [comment]
(Das obere Plus ist übrigens verlinkt mit "movieEvents/createMovieEvent/", die unteren sind nicht mit der Maus zu erreichen)

**Comment by COeins** [comment]
Okay, hab mal für die "+"-Knöpfe ein eigenes Ticket gemacht.

**Comment by Oliver3911** [comment]
Keine Probleme bei meinem FF unter Linux
![image](https://user-images.githubusercontent.com/18573108/71414047-5ea26c80-2655-11ea-99d3-09dd7f507cfd.png)

**Comment by COeins** [comment]
Nur um das klarzustellen - der Bug ist nicht "noch nicht alle Strings wurden in alle Sprachen übersetzt", sondern eher "Obwohl es einen Text in einer anderen Sprache als Fallback gibt wird trotzdem der Platzhalter angezeigt". Es ist nicht erforderlich, die App in jeder denkbaren Sprache verfügbar zu haben, aber sie sollte schon irgendwie damit klarkommen, dass jedes denkbare System Locale eingestellt ist.

**Comment by aendeavor** [comment]
@paul-mars ist das gefixt?

**Comment by paul-mars** [comment]
@aendeavor dass man das Menü nicht mehr benutzen kann wenn da zu lange Strings stehen ist gefixt, ich habe mich jedoch nicht darum gekümmert, dass die richtigen Strings erscheinen

**Comment by paul-mars** [comment]
da man alle Knöpfe benutzen kann und es hier nur noch darum geht, dass man im englischen nicht den richtigen Text hat änder ich die Priorität mal auf 4.
