### ISSUE TITLE
"Hinzufügen"-Buttons überlagern Content-Area

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#24]
Wie in #23 angesprochen tauchen im Content-Bereich Hinzufügen-Buttonsauf,dieteilweisevomInhalt überlagert werden. Hier nochmal ein Bild auf dem man das besser sieht...

**Comment by COeins** [comment]
![issue24](https://user-images.githubusercontent.com/1882002/71413803-2a7a7c00-2654-11ea-930e-a3682b5f4c80.jpg)

DieButtons sind von oben nach unten verlinkt mit dem jeweils daneben stehenden Element  (Also Filme, Events, Specials, Distros, ...)

**Comment by paul-mars** [comment]
Die Buttons sollten jetzt unabhängig von der Überlänge der Strings immer an der richtigen Stelle stehen.
