### ISSUE TITLE
At which time is the event going to start?

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#25]
At which time is the event going to start?

**Comment by COeins** [comment]
![issue25](https://user-images.githubusercontent.com/1882002/71414451-564b3100-2657-11ea-874f-fcd937ee6ad6.jpg)

**Comment by Oliver3911** [comment]
auch im deutschen:
![image](https://user-images.githubusercontent.com/18573108/71414734-8b0bb800-2658-11ea-83fd-6a1fea034458.png)

**Comment by COeins** [comment]
Eine sinnvolle Alternative wäre ohnehin, statt Start- und Endzeit lieber Start und Dauer zu erfassen. 
Da muss man weniger rechnen...

**Comment by COeins** [comment]
Hier übrigens ein weitere falsch zugeordneter Text, dafür mache ich nicht extra ein neues Ticket:
![25b](https://user-images.githubusercontent.com/1882002/71783430-ed64a100-2fe6-11ea-9af3-4f38dbe53a65.png)

**Comment by aendeavor** [comment]
Typo. Wird gefixt werden!

**Comment by aendeavor** [comment]
Done. [10.01.20-18:47]

(Wird mit dem nächsten Pull-Request durch development auf master gezogen und dann auf die VM kommen. WIrd hier zu gemacht, da es nur Typos sind.)
