### ISSUE TITLE
Sonderveranstaltungen haben keinen Dutyplan?

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#3]
auch Sonderveranstaltungen brauchen einen Dutyplan

**Comment by Andevour** [comment]
Kommt auf jeden Fall.

**Comment by Oliver3911** [comment]
@aendeavor kurzer ping, damit das hier nicht vergessen wird.

**Comment by Neolyum** [comment]
wie gestern gesehen, erledigt! :)
