### ISSUE TITLE
Broken date filter on /eventsAfter?

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#30]
Die Datenbank enthält aktuell ca 25 Events zwischen 10.12.2019 und 27.12.2019.
Davon sind 5 am 10.12., ca 20 an einem späteren Datum. 

Diese werden auch angezeigt bei 
`/eventsAfter?amount=10&start=2019-12-10T00:00`

Sobald man aber einen späteren Termin, wie z.b. 
`/eventsAfter?amount=10&start=2019-12-11T00:00`

Anfragt, bekommt man plötzlich 0 Elemente geliefert, obwohl es passende Events geben sollte.

**Comment by COeins** [comment]
PS:

der letzte funktionierende Zeitpunkt ist
`/eventsAfter?amount=10&start=2019-12-10T22:45`
ab 
`/eventsAfter?amount=10&start=2019-12-10T22:46`
geht es kaputt. 

Das ist zufälligerweise (vermutlich, da Zeitzone der Abfrage unklar) der Begin des ersten Films.

**Comment by FelixRTU** [comment]
Sollte nun funktionieren.
