### ISSUE TITLE
Dutyplan, no requst per user possible

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#31]
So wie ich das sehe, ist die einzige Methode an alle Veranstaltungen zu kommen, zu denen ein bestimmter user Dienst hat 

- alle veranstaltungen (in etreffendem Zeitraum) auflisten lassen
- jedes Element der Liste einzeln per /rest/dutyplan?eventId=XXX abzurufen
- im Client per Stringvergleich den Namen zu filtern. 

Das geht sicher sehr viel einfacher im Server. Daher bitte einen Endpunkt schaffen, der alle Veranstaltungen (in gegebenem Zeitraum) zu einer gegebenen User-ID heraussucht. 

Oder noch besser, für einen nicht erratbaren Token, der dem User zugeordnet ist. (Privacy, und so...)

also z.B. `/rest/dutyPerUser?userToken=3gdhd7GHYJh2hs&starttime=123456789&endtime=234567891`

**Comment by FelixRTU** [comment]
Ja das geht wirklich einfacher. Werde ich in Kürze erledigen (erstmal per id).

Mit dem Token das verstehe ich nicht ganz. Wenn nach einem Dienstplan gesucht wird, ist doch schon die Identität der Person klar. Wozu dann noch Anonymisieren? Oder anders herum, was nützt mir eine Auflistung von Veranstaltungen, ohne zu wissen wer dahinter steckt?

**Comment by Pollopiccante** [comment]
@FelixRTU es gibt schon eine funktion im eventmanagement um events für user zu finden, momentan per Username,
den token füge ich morgen hinzu dann kannst du es damit machen

**Comment by FelixRTU** [comment]
Ich habe jetzt die Funktionalität hinzugefügt. S.h.  #21
