### ISSUE TITLE
Can't change event's date

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#32]
Nachdem ich die Startzeit einer Veranstaltung verändert habe, lässt es sich nicht speichern. ("Something is wrong with the date/time!", s. Screenshot)

Meine Vermutung ist, dass die das Frontend englische Formatierung generiert, aber das Backend nur deutsche Schreibweise akzeptiert. Leider kann ich nicht ohne weiteres den Output des Datepickers ändern um die Vermutung zu testen.

Dieser Fehler tritt auch auf, wenn man die Seite einfach nur lädt und "Speichern" klickt, ohne irgendwas zu ändern. 

Witzigerweise wird das Enddatum anscheinend nicht (nach den gleichen Regeln?) validiert...

**Comment by COeins** [comment]
![32](https://user-images.githubusercontent.com/1882002/71772706-d6bf3b00-2f4f-11ea-9e98-6a31ac7ab8b0.png)

**Comment by Oliver3911** [comment]
same in deutsch
![image](https://user-images.githubusercontent.com/18573108/71772779-5f8aa680-2f51-11ea-876b-14da6a746390.png)

**Comment by COeins** [comment]
Hm... Dann hat es wohl eine andere ursache...

**Comment by aendeavor** [comment]
@COeins Das Datum von Events in der Vergangenheit zu bearbeiten, daran hatte ich gedacht, dass das notwendig werden würde.

Ich kann das ändern - bitte prüf aber mal, ob du zu diesem Event ein Datum eingegeben hast, welches nicht zu der Buchung des Events passt. Das wäre ein legitimer Fehler der auch als solcher gehandled werden soll.

Was es mit dem Datumsformat auf sich hat, werde ich mir anschauen.

**Comment by aendeavor** [comment]
Sollte nun gefixt sein. Doch bevor dieser Issue geschlossen wird, warten wir noch ab, bis wir sicher sind.
