### ISSUE TITLE
Non-Default movie poster ruins table lauout

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#33]
Wenn das Filmplakat nicht das gleiche Seitenverhältnis hat wie die andern sieht die Tabelle, gelingt gesagt "unschön" aus. Das Bild sollte hier entweder zugeschnitten oder sonstwie begrenzt werden...

**Comment by COeins** [comment]
![33](https://user-images.githubusercontent.com/1882002/71772829-7e3d6d00-2f52-11ea-8e27-865cab6f8ad6.png)

**Comment by paul-mars** [comment]
Auf dem GUI branch wird es nun weiterhin 1 zu 1 übernommen, jedoch sollte das Tabellen Layout nicht mehr beeinflussen.

**Comment by FelixRTU** [comment]
fixed
