### ISSUE TITLE
Original title when creating a booking

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#34]
Beim Anlegen einer Buchung sollte immer der deutsche Titel verwendet werden 
(Da dieser im Gegensatz zum Originaltitel nicht optional ist und vom Verleih auch i.d.R. so auf der TB angegeben wird)

**Comment by COeins** [comment]
Nachtrag: Das gilt natürlich für die gesamte Kommunikation mit dem Verleiher, also auch für das Generieren der PDFs.

**Comment by Nawatix** [comment]
@Neolyum hab das in der Buchung gefixt, könntest du bitte in der PDF nochmal gucken ob du da den deutschen Titel nimmst

**Comment by Neolyum** [comment]
Done :)
