### ISSUE TITLE
"Load next events" doesn't turn back

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#35]
Meine Erwartung war, dass "Load Next Events" einfach die Liste um die nächsten Veranstaltungen verlängert. Statt dessen funktioniert es wie ein "Weiterblättern"-Button. Auch gut. Nur gibt es leider keinen "Zurück"-Button. Was die Navigation etwas mühselig macht.

**Comment by aendeavor** [comment]
Wird erledigt, hatte ich auch bereits dran gedacht :D

**Comment by aendeavor** [comment]
Done. [10.01.20-18:55]

Es gibt nun die Option, zurückzugehen und noch mehr: Nun werden alte Events sauber getrennt, und ihr seht sie separat, wenn ihr das wollt und den Link klickt.

(Kommt mit dem Pull über das Wochenende.)
