### ISSUE TITLE
Fehlerhafte Abrechnung

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#36]
Die Kartennummern werden bei der Eingabe im Frontend korrekt angezeigt, 
z.B. "1 bis 2, 2 verkaufte, Preis X*2"
in der PDF jedoch als 
"1 bis 2, 1 verkaufte, Preis X"
ausgewiesen. 

Außerdem wird, obwohl im Frontend gesagt wird, dass SPIO erst ab 2 Veranstaltungen fällig wird, der Betrag auch bei nur einer Veranstaltung mit berechnet.

**Comment by aendeavor** [comment]
@Nawatix bitte mal nachprüfen und der Sache auf den Grund gehen. Falls in den Tickets falsch abgerechnet wird, mir sagen oder selbst einfach schnell korrigieren.

@Neolyum falls das Problem in der Abrechnung ist, hier bitte Bescheid sagen

**Comment by Neolyum** [comment]
ich nutze
`reducedCardSum += e.getTickets().getReducedCount();`
Damit rechne ich weiter, denke also, der Getter verschweigt mir ein Ticket, da ich sonst keine weitere Logik habe ^^

**Comment by aendeavor** [comment]
@Neolyum also, @Nawatix hat meinen kleinen bug gefixt. Du kannst auch von den Tickets gleich kalkulieren lassen, wenn du willst. Die Methoden stehen zur Verfügung. Die Buchung macht es so.

@Nawatix Die Tickets rechnen nun also richtig ab :D 

Ich unassigne mich hier, und denke fast, dass der Issue _Done._ ist.

@COeins wenn die neue Version über das Wochenede fertig ist, solltet ihr sehen können, ob der Fehler noch besteht. Falls nicht mehr, kannst du ja diesen Issue hier schließen:)

**Comment by COeins** [comment]
Das PDF sieht tatsächlich jetzt besser aus. Was aber immer noch unklar ist, ist die Zahl unter "Gesamter Umsatz". Entweder verstehe ich hier nicht wie das berechnet werden soll (da sich die Zahl so nirgendswo im PDF wiederfindet), oder eine falsche Formel ist noch an anderen Stellen im Einsatz...

Im Anhang ein Beispiel-Bild:
![36](https://user-images.githubusercontent.com/1882002/72281434-da7f4b80-363a-11ea-8cd5-092ca323b3fe.jpg)

**Comment by Nawatix** [comment]
@COeins gemeint ist mit 'Gesamter Umsatz' der Netto-Erlös, das werde ich gleich noch umbenennen. Der Fix für die falsche Berechnung existiert schon, befindet sich aber noch nicht auf dem server

**Comment by COeins** [comment]
Sehr gut. Dann bleibt bloß noch der Punkt, dass der SPIO-Betrag erst ab 2 Veranstaltungen fällig wird. Das ist aktuell noch nicht berücksichtigt.

**Comment by Neolyum** [comment]
Im nächsten Merge dabei! :)

**Comment by Oliver3911** [comment]
eben kam noch folgender wichtiger hinweis zur abrechnung:

```
okay, ich habe auch noch einen wichtigen fehler in der abrechnung entdeckt: 
Es ist leider etwas kompliziert...
wenn ihr euch mal so ein abrechnungsbogen (pdf) vornehmt, handelt es sich bei dem "Netto-Erlös", um 107 %. Entsprechend müsste der Dreisatz da angepasst werden. Man muss also von den 107 % Netto-Umsatz, durch die Subtraktion von 7 % MwSt., auf 100 % Brutto-Erlös kommen.
Aktuelle wird so gerechnet, dass von 100 auf 93 % gerechnet wird. Das ist falsch.
Der Prozentsatz in den Buchungskonditionen wird dann vom Bruttoerlös verwendet, auf den dann wiederum 7 % Mehrwertsteuer kommen... ;) 
Um das deutlich zu machen, habe ich mal einen Film mit übertrieben hohen Kartenverkaufszahlen angelegt (Kokowääh)

Ich hoffe das ist alles nachvollziehbar
```

Ebenfall wichtig!
```
Zuletzt muss auch noch dringend der Begriff "Gutschrift" auf die Abrechnung. Einfach in den Betreff, also "Spielfilmsteuerabrechnung/ Gutschrift"
```

**Comment by Oliver3911** [comment]
ebenfalls wenn der admin von einer abgerechneten buchung die tickets ändert, scheint dies nicht die abrechnung zu verändern. ein knopf für den abmin um eine erneute abrechnung auszulösen wäre gut

**Comment by Neolyum** [comment]
die Falsche PDF Logic ist im Nächsten Merge mit drin!

**Comment by Nawatix** [comment]
> 
> 
> ebenfalls wenn der admin von einer abgerechneten buchung die tickets ändert, scheint dies nicht die abrechnung zu verändern. ein knopf für den abmin um eine erneute abrechnung auszulösen wäre gut
> bzw den status auf nicht abgerechnet zurück setzen, was besser geht

@Oliver3911 Das klicken auf abrechnen setzt lediglich den status der buchung sowie den status aller verknüpften events auf abgerechnet, es werden keine werte festgesetzt. Sowohl die Eventanzeige in der Detailansicht der Buchung als auch die PDF (@Neolyum korrigiere mich wenn ich falsch liege) ziehen sich stets die aktuellen Werte (Ticketnummern) der Events. Dementsprechend sollte das von dir erwähnte verhalten nicht auftreten. Habe grade nochmal selbst die tickets eines events einer abgerechneten buchung geändert und die werte haben sich in der buchung angepasst wie sie es sollten. Wenn ich auf PDF generieren geklickt habe, hatte die PDF auch die neuen tickets eingetragen. Vllt. missinterpretiere ich auch worauf du hinaus willst?

**Comment by Oliver3911** [comment]
> ebenfalls wenn der admin von einer abgerechneten buchung die tickets ändert, scheint dies nicht die abrechnung zu verändern. ein knopf für den abmin um eine erneute abrechnung auszulösen wäre gut
> bzw den status auf nicht abgerechnet zurück setzen, was besser geht

@Nawatix ich habe das ganze gerade auch noch mal durchgespielt und scheinbar gab es zwischen mir und denjenigem dem das aufgefallen ist einen Kommunikationsfehler. (habe habe ihn falsch verstanden)
So wie es jetzt ist, ist es super. Kein eingreifen nötig.

_Aber_ ich hätte da zwei kleine **Nice to Have** Dinge, wenn noch zeit ist. **Wenn nicht kann das issue einfach geschlossen werden!**

- [ ] Button für den Admin um eine Buchung im Status "Abgerechnet" wieder zu öffnen

- [ ] Wenn eine Buchung im Status A"bgerechnet" ist, wäre es schön wen nur der Admin noch die Tickets editieren kann

**Comment by Nawatix** [comment]
@aendeavor falls du das umsetzen möchtest, dass nur noch der admin die tickets ner abgerechneten Veranstaltung editieren darf, kannst du das gerne machen. Wenn nicht kannst du das issue einfach schließen :)
