### ISSUE TITLE
Timezone unclear when creating events

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#37]
Wenn ich eine Veranstaltung um "20:30" anlege (aktueller Default), dann erwarte ich eigentlich, dass es sich dabei im Mitteleuropäische (Sommer-) Zeit handelt. Tatsächlich ist es (laut API-Abfrage) aber wohl UTC. 

Bitte ändert das, oder macht es zumindest klarer deutlich, sonst sehe ich schon viel Verwirrung voraus...

edit: Ich sehe, es ist noch verwirrender. Was ist bitte der Unterschied zwischen

"start":"20:30Z",
"odt":"2020-03-27T19:30:00Z"

(gleiches Event, unterschiedliche Zeit? Je nachdem welche Zeit man jetzt als gültige Startzeit annimmt, war die Eingabe im Frontend jetzt entweder in UTC oder in UTC+1... :verwirrt:)

**Comment by COeins** [comment]
Um das Positive auch zu erwähnen, ein in der Sommerzeit-Periode angelegtes Event ist jetzt entweder UTC+1 oder UTC+2 zugeordnet, je nachdem welches Feld man als Referenz nutzt.

**Comment by aendeavor** [comment]
@COeins das ist lediglich ein in der API Abfrage schlecht zu erkennender Umstand.

Der Wert `"start" : "20:30"` ist hierbei die in der Zeitzone "Berlin" tatsächlich vorhandene Uhrzeit, währendt es sich bei `"odt" : "2020-03-27T19:30:00Z"` (eigentlich `"2020-03-27T19:30:00Z+01:00"`) um die sogenannte OffsetDateTime handelt.

Die OffstetDateTime speichert den UTC timespamp, und den Offset (die Zietzone) extra. Im Event liegt also alles richtig - die API Dokumentation wird das auch erklären.

**Comment by COeins** [comment]
> Coordinated Universal Time (UTC)
> If the time is in UTC, add a Z directly after the time without a space. Z is the zone designator for the > zero UTC offset. "09:30 UTC" is therefore represented as "09:30Z" or "0930Z". "14:45:15 UTC" 
> would be "14:45:15Z" or "144515Z". 

Daher ging ich davon aus, dass "start":"20:30Z" UTC sein müsste. Falls dieser Wert Ortszeit sein soll, dann bitte mindestens das "Z" entfernen. Besser gleich die richtige Zeitzone einfügen, um alle Missverständnisse zu vermeiden. (Also z. B. "20:30+01")

**Comment by FelixRTU** [comment]
Ich habe jetzt odt entfernt und den Start mit einer Zeitzone versehen.
