### ISSUE TITLE
Event ohne verkaufte Karten kann nicht abgrechnet werden

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#38]
... selbst wenn Freikarten in der Veranstaltung eingetragen wurden. 

Wir müssen den Fakten ins Auge sehen. Es kommt leider hin und wieder mal vor, dass niemand unsere Filme sehen will. Der Verleih will trotzdem seine Abrechnung (und die darin enthaltene Mindestgarantie) haben.

Auẞerdem kommt es häufiger vor, dass wir Filme ohne Eintritt zeigen, sprich alle "verkauften" Karten sind Freikarten. 

Beides führt aktuell dazu, dass der Film nicht abgerechnet werden kann.

**Comment by aendeavor** [comment]
Done. [10.01.20-18:50]

(Kommt mit dem nächsten Pull, sollte also über das Wochenende da sein.)
