### ISSUE TITLE
Abrechnung kann keine Sonderzeichen

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#39]
... und da die Abrechnung derzeit noch den Originaltitel als Referenz benutzt, führt das derzeit zu Abrechnungen ohne Filmtitel:

![39](https://user-images.githubusercontent.com/1882002/71783514-fdc94b80-2fe7-11ea-9f04-cfc8e63c44e7.png)

**Comment by Neolyum** [comment]
der deutsche Titel ist jetzt Standart, sonderzeichen zeigt er auch an, zumindest umlaute hab ich getestet. Emojis funktionieren leider nicht :worried:
