### ISSUE TITLE
Can't create new movie

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#40]
Aus irgendeinem Grund kann ich keine Filme mehr erstellen. Egal was ich eingebe, ich bekomme immer den folgenden Fehler:

> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> Sun Jan 05 17:29:31 UTC 2020
> There was an unexpected error (type=Internal Server Error, status=500).
> Index 0 out of bounds for length 0

Da das bereits einmal funktioniert hat sage ich mal ganz fresch, dafür sollte es einen Unit-test geben.

**Comment by FelixRTU** [comment]
Sollte bei dem nächsten merge auf Master erledigt sein.

**Comment by FelixRTU** [comment]
fixed
