### ISSUE TITLE
Unübersichtliche "Übersicht"

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#41]
Die Ansicht "Übersicht" enthält derzeit 25 Monats-"Kacheln", von denen gerade mal 2 Werte verschieden von 0 haben. Dadurch habe ich einen recht langen Scroll-Bereich. Wo kommt eigentlich der Wert 25 her?

Da wir im KiK an den Semester-Rhythmus der Uni gekoppelt sind, ist davon auszugehen, dass es immer mal wieder Monate gibt, in denen keine Veranstaltungen stattfinden. 

Daher folgende Wünsche:

* defaultmässig Kacheln aus den letzten 12 Monaten anzeigen. 
* Monate, in denen keine Veranstaltungen gelaufen sind, ausblenden
* Bonus: (z.B. per Drop-down Menü) den angezeigten Bereich verkürzen/verlängern.

**Comment by FelixRTU** [comment]
Punkt eins und zwei sind erledigt.

**Comment by COeins** [comment]
In Anbetracht der fortgeschrittenen Zeit bin ich mit 2/3 zufrieden :)
