### ISSUE TITLE
"My Jobs" contains past shifts

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#42]
Es mag ja durchaus hin und wieder Gründe geben, warum man sich die Schichten der Verganagenheit anschauen will (von "Wer hat den Kühlschrank nicht aufgefüllt" bis zu "Mitarbeiter der Monats"), aber in erster Linie dient diese Ansicher der Frage "Wann bin ich das nächste mal dran?" Und dafür ist es nicht sinnvoll, wenn ich mich erst Seitenweise durch alte Events klicken muss, bis ich irgendwann in der Gegenwart angekommen bin.

Daher meine einfache Bitte: Alle Schichten in der Vergangenheit auf dieser Ansicht ausblenden.

**Comment by Oliver3911** [comment]
Kann es sein das hier Jobs für den aktuellen Tag nicht angezeigt werden?
![image](https://user-images.githubusercontent.com/18573108/72054520-6c98f400-32c9-11ea-8736-8bdc76a9c70d.png)
![image](https://user-images.githubusercontent.com/18573108/72054549-79b5e300-32c9-11ea-993e-7806aad77117.png)

Wenn ja bitte Jobs die "heute" stattfinden in der Liste angezeigt lassen

**Comment by Pollopiccante** [comment]
Ja heute wurde fälschlicherweise zu den vergangenen tagen gezählt.
Sollte morgen dann gefixt auf dem server sein

**Comment by Pollopiccante** [comment]
Jetzt wird heute angezeigt
