### ISSUE TITLE
Externe Abhänigkeiten vermeiden

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#43]
Bitte Libs und Fonts lokal hosten und nicht von extern laden.

![image](https://user-images.githubusercontent.com/18573108/71827796-455fde00-30a1-11ea-90ab-178ae831bca3.png)

**Comment by Nawatix** [comment]
Es sollten jetzt alle Abhängigkeiten lokal gehostet werden.
