### ISSUE TITLE
Test Instanz nicht funktionsfähig

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#44]
Wie gestern besprochen, schaut doch mal bitte das ihr die Version auf dem Test Server wieder start fähig bekommt.
Wenn dafür ein Eingriff von uns nötig ist gebt mir hier einfach einen Ping oder ein @all im Chat.

**Comment by aendeavor** [comment]
Da das immer noch ein Praktikum und keine Vollzeitarbeit ist, kann es passieren, dass es einmal mehr als 24 Stunden daurt. Der Testserver ist aber bereits wieder online.

**Comment by COeins** [comment]
Wie - Praktikum? Warum sagt uns das keiner vorher??? ;)
