### ISSUE TITLE
Broken Layout auf "Movie Events" seite

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#45]
Siehe Bild.

**Comment by COeins** [comment]
![45](https://user-images.githubusercontent.com/1882002/71938880-18025580-31b1-11ea-9ac6-e9ce1a1c78c3.png)

**Comment by Oliver3911** [comment]
Der Header ist auch kaputt.
Der Fehler passiert auch auf der Übersichtsseite wenn man sich zB in einen Job einträgt.

**Comment by Neolyum** [comment]
Fixed!

**Comment by Oliver3911** [comment]
@Neolyum der auf der Live Version noch kaputten Version geht auch der Knopf rechts oben mit dem Namen zum zB logout nicht

**Comment by Neolyum** [comment]
@Oliver3911 das ist eigentlich unabhängig von der Seite selbst, sollte wenn global funktionieren oder nicht.
