### ISSUE TITLE
Als Admin kann ich im Dutyplan...

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#46]
... zwar anderen Leuten Jobs zuordnen, aber es gibt aktuell keine Möglichkeit, diese wieder zu löschen. Nur mich selbst kann ich unsubscriben. 

Dass der Unsubscribe-Vorgang noch etwas überarbeitet werden soll hatten wir ja schon besprochen. Das bitte gleich mit berücksichtigen.

**Comment by Neolyum** [comment]
Done :)
