### ISSUE TITLE
Fehlende Auslog/Hover/Klickfuntion beim Usernamen 

### ISSUE THREAD

**Issue by glombart** [kino-im-kasten/SWT2019#47]
1. Der Pfeil beim Usernamen suggeriert ein Dropdownmenü.  (Zum Ausloggen etc.)
Allerdings erscheint dort nichts, egal ob hovern oder klicken.

2. Mir fehlt generell eine Auslogfunktion, oder übersehe ich die gerade?

Tested on Firefox 72.0.1 (64 Bit) Linux

![image](https://user-images.githubusercontent.com/15110541/72069991-be04ab80-32e8-11ea-8af5-f33cbd087954.png)

**Comment by Oliver3911** [comment]
siehe auch #45

**Comment by COeins** [comment]
Hab auch gerade erfolglos nach dem Logout gesucht. Das sollte schon irgendwo verfügbar sein...

**Comment by paul-mars** [comment]
Das Dropdown-Menü mit logout-Button erscheint nun auf development wieder
