### ISSUE TITLE
Fehlender Infotext beim User unlock Dialog

### ISSUE THREAD

**Issue by glombart** [kino-im-kasten/SWT2019#48]
Nachdem man als Admin einen neuen User angelegt hat, und dieser sich das erste Mal einloggt erscheint dieser nichtssagende Dialog:

![image](https://user-images.githubusercontent.com/15110541/72071347-dfb36200-32eb-11ea-876f-242225a21a9b.png)

Tested on Firefox 72.0.1 64bit Linux

**Comment by Oliver3911** [comment]
beim ersten login wird ein neues passwort abgefragt, was du leider nicht lesen kannst.
(wundere dich nicht ich habe mich mit dem user vorhin eingeloggt, da stand Oliver ^^)

**Comment by Pollopiccante** [comment]
Das sollte morgen weg sein, habe die placeholder gerade auf developement gepusht

**Comment by Pollopiccante** [comment]
Habe gerade mal meinen Browser auf englisch umgestellt, hat funktioniert.
