### ISSUE TITLE
User exists after deletion

### ISSUE THREAD

**Issue by glombart** [kino-im-kasten/SWT2019#49]
1. User erstellen
2. User löschen
3. User mit selbem Namen erstellen
4. Fehlermeldung (siehe Bild)

Nach Löschen eines Users würde ich erwarten, dass auch wirklich gelöscht ist.

![image](https://user-images.githubusercontent.com/15110541/72070986-18067080-32eb-11ea-9823-14607fe2509b.png)

Tested on Firefox 72.0.1 64bit Linux

**Comment by Oliver3911** [comment]
Das ist ein gewolltes verhalten, gelöschte unser wandern in den "papierkorb" sollte man sie wiederherstellen wollen.
Die bessere beschriftung hier wäre vllt user sperren und unter gesperrte user dann den knöpf löschen.

**Comment by COeins** [comment]
Außerdemst würde man selbst dann nicht wollen, dass ein neues Nutzer unter dem Namen eines alten Nutzers weitermacht. Das würde auf allen Seiten nur für Verwirrung sorgen.

**Comment by Pollopiccante** [comment]
Es wird jetzt "in Papierkorb verschieben" und "UNWIEDERHERSTELLBAR löschen"
beim löschen angezeigt, ist das für euch in Ordnung?

**Comment by COeins** [comment]
Passt.
