### ISSUE TITLE
Konsistente Daten (SQL DB)

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#5]
Werden Daten aktuell nicht gespeichert weil die SQL DB noch nicht in Verwendung ist?
Wann wird diese verwendet werden?

**Comment by Neolyum** [comment]
Die SQL Datenbank ist schon aktiv, es kann sein, dass die DB in den ersten Tagen von git pull oder solches überschrieben worden ist. Sollte inzwischen alles funktionieren!
