### ISSUE TITLE
Dialogbox zu klein

### ISSUE THREAD

**Issue by glombart** [kino-im-kasten/SWT2019#50]
Beim Erstellen einer Filmveranstaltung ist die Dialogbox für die Filmbeschreibung (Description) viel zu klein.

![image](https://user-images.githubusercontent.com/15110541/72071715-bb0bba00-32ec-11ea-917b-a3c8f7579375.png)

**Comment by Oliver3911** [comment]
In Chrome kann man die selbst größer machen.
Wenn dies auch in Firefox möglich zu machen wäre, wäre dies nett. Aus gründen der übersicht würde ich eine große leere box aber nicht bevorzugen.
Nice to have ^^

**Comment by glombart** [comment]
Stimmt in Firefox, kann man die Dialogbox auch größer ziehen.
Wäre aber schön, wenn man einen größeren Text kopiert/verfasst, dass die Box dynamisch mitwächst.

Allerdings finde ich den Default einfach zu klein gesetzt. Die Standardfilmbeschreibungen sind definitiv länger als 2 Zeilen…

**Comment by paul-mars** [comment]
Ich werde es auf jeden Fall größer machen, ob ich euch das manuelle Resizen ersparen kann muss ich aber nochmal schauen, allerdings ist das nicht ganz ohne Weiteres möglich. :crying_cat_face:

**Comment by Oliver3911** [comment]
automatisches resizen ist ein absolutes nice to have, also nicht zu viel zeit rein hauen.
Viel wichtiger ist das im Beschreibungsfeld mehr Text hinterlegt werden kann.
siehe https://github.com/kino-im-kasten/SWT2019/issues/51#issuecomment-572572802

Zum Testen einfach mal auf die Webseite schauen wie lang dort unsere Texte so werden ^^

**Comment by paul-mars** [comment]
Dialogbox passt sich auf development nun an die geschriebenen Zeilen an.
