### ISSUE TITLE
(Fehlende) Fehlermeldung bei Filmerstellung

### ISSUE THREAD

**Issue by glombart** [kino-im-kasten/SWT2019#51]
Filmerstellung mit Daten aus https://github.com/kino-im-kasten/SWT2019/issues/50#issue-547479786

+ Trailer: https://vimeo.com/56980279
+ folgendem Poster: https://image.tmdb.org/t/p/original/hnYowHwLq0iUWriAHtiiCWsI2dP.jpg

Hinterlässt mich nach Buttonklick, mit folgendem leeren Fenster:

![image](https://user-images.githubusercontent.com/15110541/72072197-b4317700-32ed-11ea-927b-8dc6cabde14b.png)

Man kann nur anhand des Browsertitels erkennen, dass überhaupt etwas schief gegangen ist. Unklar ist für mich noch woran es gescheitert ist:

Möglichkeiten:
1. Japanische Zeichensatz nicht unterstützt.
2. Description zu lang
3. Probleme mit Trailer oder Bild?

**Comment by glombart** [comment]
Habs nochmal mit Minimalbeispiel probiert:

1. Japanische Zeichen sind unterstützt. yay!
Es liegt an der Description, wenn ich die Description zu lang mache, dann failed es wie oben im Bild

**Comment by Oliver3911** [comment]
Fun Fact gibt man eine Absurd größe Zahl bei Laufzeit an bricht der Vorgang auch ohne Fehler ab.

**TODO**

- [ ] Speicherfeld bei Beschreibung vergrößern
- [ ] sanity checks für alle Felder und/oder
- [ ] Fehlermeldung

**Comment by paul-mars** [comment]
Das leere Fenster ist da weil die Fehlermeldung auf dem Server aktuell noch leer ist, eine Standard Fehlermeldung ist bereits auf Development und wird auch bald den Server erreichen.

**Comment by FelixRTU** [comment]
Es werden jetzt alle Felder auf ihre Länge überprüft und entspechende Fehler werden angezeigt. Sollte ein unbekannter Fehler auftreten, wird ein Ausschnitt auf der Seite angezeigt.

Die Zeichenbeschränkungen der Felder sind wie folgt:

- Beschreibung: 15000
- Laufzeit: 5
- Alle anderen Felder außer Erscheinungsjahr: 150

Momentan ist es noch so, das es keine Zeilenumbrüche der Textfelder auf der Detailseite gibt, wen die da sind, sollte auch der Rest den ich gerade beschrieben habe, verfügbar sein.

**Comment by FelixRTU** [comment]
Die richtige Formatierung kommt etwas später.
