### ISSUE TITLE
IE11 Layout kaputt

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#52]
Im IE11 zerreißt es kommt das Layout der Seite.
Aber mal ehrlich wen interessiert. Dieses Issue dient nur der Belustigung

![image](https://user-images.githubusercontent.com/18573108/72074129-9d8d1f00-32f1-11ea-90f3-e27ddbb69d08.png)

**Comment by COeins** [comment]
Da es ohnehin auf wontfix steht mache ich er der übersichtlichkeit halber hier mal zu
