### ISSUE TITLE
Nach Login Redirect zu :80

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#53]
Nachdem ich mich eingeloggt habe, werde ich automatisch zu Port 80 (unverschlüsselt) umgeleitet.

Dies ist in sofern ungünstig, da in diesem redirect mein Session-Cookie gerade unverschlüsselt übertragen wurde. Sprich, selbst wenn wir die User anschließend wieder auf Port 443 zurückumleiten, wäre sie Session unsicher. Erinnert sich noch jemand an Firesheep?

Um das besser beobachten zu können habe ich Port 80 mal auf eine Fehlerseite umgeleitet. Man kann das Portal normal weiter benutzen, indem man manuell wieder auf https wechselt.

**Comment by COeins** [comment]
![53](https://user-images.githubusercontent.com/1882002/72192041-7b37f600-3404-11ea-9d58-5c1d70919e63.png)

**Comment by COeins** [comment]
Das gleiche passiert übrigens auch nach dem Logout (sieht man bloß nicht weil #47 )

**Comment by COeins** [comment]
Ich möchte an dieser Stelle auf RFC 7231 hinweisen, der durchaus auch relative Links in Redirects erlaubt: https://tools.ietf.org/html/rfc7231#section-7.1.2

Es ist also keinesfalls erforderlich, jedes mal das Protokoll (oder die Domain) zu erraten. Man kann das einfach dem Browser überlassen...

**Comment by Oliver3911** [comment]
der redirect zu http passiert auch beim anlegen bzw löschen von Nutzern.

**Comment by COeins** [comment]
Der Redirekt tritt auch beim Zugriff auf die API hin und wieder mal auf. Ich verstehe allerdings nicht ganz, wann genau und warum. Eigentlich sollten alle anfragen doch gleich behandelt werden?

**Comment by FelixRTU** [comment]
Ich kann nur von API sagen, das alle Anfragen vom Typ Get sind und gleich behandelt werden. Von dem was Spring im Hintergrund macht, habe ich keine Ahnung. 

Offenbar tritt der Fehler besonders bei POST Requests auf, welche beim anlegen/löschen/bearbeiten genutzt werden.

**Comment by Neolyum** [comment]
Die Forward headers sind nun korrekt gehandled!
