### ISSUE TITLE
Cant click on the right-most job in Dutyplan

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#54]
Der am weitesten rechts stehende Job lässt sich nicht (un-)assignen, da er immer, wenn man im mit der Maus zu nahe kommt vom Popup versteckt wird :)

**Comment by COeins** [comment]
![54](https://user-images.githubusercontent.com/1882002/72192635-bf2bfa80-3406-11ea-9b2e-366f97a8ab46.png)

**Comment by Neolyum** [comment]
Bis das gefixt ist, ein kleiner Workaround ist zu versuchen, direkt links vom Popup den Link des Jobs zu treffen, der ist bei 1080p bei mir etwas breiter als das Popup :)

**Comment by paul-mars** [comment]
Ich habe jetzt auf Development die Jobs in eine neue Reihe gepackt, weil das dächte ich sowieso erwünscht war und somit auch dieser Fehler nicht mehr vorkommt.
