### ISSUE TITLE
Leerer Buchungs-Titel beim Anlegen von Filmevents

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#55]
Wie kann das sein, der Filmtitel ist doch ein Pflichtfeld?

**Comment by COeins** [comment]
![55](https://user-images.githubusercontent.com/1882002/72192953-d3242c00-3407-11ea-9ed7-5b1f1b95d0fd.png)

**Comment by FelixRTU** [comment]
Das Problem ist das gleiche wie in #34 . Wird ein Film ohne Originaltitel gewählt, tritt das Problem auf.

**Comment by Nawatix** [comment]
Fix hab ich grade auf development gemerged

**Comment by aendeavor** [comment]
Der Fehler existiert aber noch, wird in der Liste der FIlmveranstaltungen immer noch nicht angezeigt. Bitte schnell darum kümmern - einfach eine neue Buchung anlegen und testen @Nawatix

**Comment by Nawatix** [comment]
@aendeavor Die Funktion, die den 'Identifikationsstring' generiert nimmt einfach den deutschen titel des filmes als erstes element, der ja immer existieren sollte. Habe gerade einen Film ohne Originaltitel erstellt und darauf ne Buchung und alles läuft wie geschmiert. Hast du den aktuellen Stand bzw. wie ist der Fehler aufgetreten?

**Comment by aendeavor** [comment]
@Nawatix 

Steps to recreate:

1. Neuen Film anlegen (nur mit den auszufüllenden Feldern)
2. Neue Buchung mit diesem Film anlegen
3. Filmveranstaltung mit diesem Film anlegen

Ich schaue jetzt mit dem Debugger nach

**Comment by aendeavor** [comment]
Sollte jetzt gefixt sein - ich habe den OriginalName und nicht den GermanName genommen.
