### ISSUE TITLE
Filmbilder in API

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#56]
Mir ist gerade aufgefallen, dass es aktuell keine Möglichkeit gibt, die Filmbilder (z.b. als Link) aus der API auszulesen. Die sollen ja, wie man sich z.b. auf www.kino-im-kasten.de anschauen kann, im Programm angezeigt werden. Wäre schön, wenn ihr das noch ergänzen könntet...

**Comment by FelixRTU** [comment]
Das ist möglich, dafür ist die "pictureId" vorgesehen. Es muss nur eine Anfrage an /movies/image/[ID] gemacht werden und das Bild wird zurückgegeben. Wäre euch ein Link lieber?

**Comment by COeins** [comment]
Nö, können wir auch so lassen. Ich konnte nur ohne Erklärung mit dem Feld nichts anfangen.
