### ISSUE TITLE
PDF Dateiname

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#57]
Es wäre schön wenn der Buchungsname im Dateinnamen steht statt "_tmp_Buchung" 
Der Timestamp könnte auch am anfang stehen, wenn der nicht so lang ist. Datum würde wohl reichen, Uhrzeit kann weg.

Statt "_tmp_Buchung 2020-01-14T10_13_16.4884232077946847882638806.pdf"
also: "2020-01-14_The Dark Knight.pdf" zB

**Nice to have**

**Comment by Neolyum** [comment]
da ich javas eigene Temp-File generation benutze, scheine ich keine große Kontrolle über die Benennung zu haben :( zudem scheint java Probleme mit der Benennung von Linux Ordnerstrukturen zu haben, das _tmp_ kann ja eigentlich nur ein /tmp/ gewesen sein. 
Ich habe die Dateien aber jetzt so umbenannt, dass sie nach Art 
_tmp_2020-01-14_The Dark Knight2134234234234.pdf
heißen. Ich hoffe, das trägt schon zur Übersichtlichkeit bei!

**Comment by Oliver3911** [comment]
@Neolyum jop das is schon mal besser, danke

**Comment by Neolyum** [comment]
Die Pdf heißt nun
`2020-01-14_The Dark Knight2134234234234.pdf`
Ich vermute, ich bekomme die Zahlen am ende nicht weg, so ist auch sichergestellt, dass jede generation eine andere zahl hat, und niemals Abrechnungen überschrieben werden!
