### ISSUE TITLE
Buttons "deleted users" und "existing users" vertauscht. 

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#58]
Wenn ich zu den gelöschten Leuten will, muss ich auf "existing" klicken. Das ist etwas unintuitiv...

(ich kann gerade nicht sagen wir es in der deutschen Version ist, vielleicht ja nur ein übersetzungsbug)

**Comment by aendeavor** [comment]
@Pollopiccante hier kann man sich auch selbst assignen...

**Comment by Pollopiccante** [comment]
Eigendlich war das sogar so gedacht, als eine art umschaltknopf, der anzeigt was gerade sngezeigt wird quasi als überschrift

**Comment by Pollopiccante** [comment]
Ich könnte ja ein feld
"Gerade angezeigt: " machen
Kanns aber auch vertauschen

**Comment by Oliver3911** [comment]
Glaube ich gerne, aber gerade bei der ersten Nutzung erwartet man nicht das ein druck auf "existierende Benutzer einen zum Papierkorb führt ^^
Knopfbeschriftung tauschen ist auf jedenfall Nutzerfreundlicher.
Vllt (=nice to have) kann man sogar noch eine Überschrift einfügen die einem sagt wo man gerade ist ;-)

**Comment by Pollopiccante** [comment]
es wird jetzt angezeigt welche Benutzer man gerade sieht,
und der Knopf zeigt verständlich an wo es hingeht wenn man ihn drückt :)
ich machs mal zu
