### ISSUE TITLE
Whitelabel Error Page bei fehlenden Rechten

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#6]
Normaler User bekommt die Fehlerseite wenn man versucht auf edit zu klicken wo man es nicht darf.

**Vorschlag** edit Knopf ausblenden wenn man ihn nicht nutzen darf.
(vllt einen anderen Fehler Hinweis bauen, was unnötig ist wenn diesen nicht erreichen kann, weil die Knöpfe nicht da sind) ^^

![image](https://user-images.githubusercontent.com/18573108/71179174-ee1fd800-226f-11ea-89ec-4bac80025adc.png)

**Comment by COeins** [comment]
Ich würde nicht sagen, dass es unnötig ist eine Fehlerseite zu hinterlegen. Es ist davon auszugehen, dass es immer zu unvorhersagbaren Fehleren kommt und es wäre schön, wenn es eine entsprechende Meldung statt dieser Whitelabel-Seite gäbe. 

(Trotzdem sollte dieser Fehler natürlich behoben werden)

**Comment by FelixRTU** [comment]
Das sieht ja mitlerweile so aus. Sollte eigentlich ausreichend sein.

![grafik](https://user-images.githubusercontent.com/44712718/72527177-7510a200-3868-11ea-9c04-736a301b7c72.png)

**Comment by Oliver3911** [comment]
Ich mache das Ticket hier mal mit verweiß auf meinen Kommentar https://github.com/kino-im-kasten/SWT2019/issues/7#issuecomment-574093522 zu
