### ISSUE TITLE
Database backend

### ISSUE THREAD

**Issue by COeins** [kino-im-kasten/SWT2019#61]
Ist eigentlich noch geplant, die bereitliegende MySQL Instanz anzubinden?

**Comment by Oliver3911** [comment]
dachte ist sie schon lange siehe #5

**Comment by aendeavor** [comment]
Endlich funktioniert es, und ist damit wirklich gefixt. Kann man gerne betrachten. Damit ist das hier

Done. [16.01.20-18:11]
