### ISSUE TITLE
Lade vorherige/nächste Buttons bei ...

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#62]
- Buchungen
- Verleiher
- Film

**Comment by Oliver3911** [comment]
Beschriftung der Knöpfe etwas kürzer, wäre der Übersicht zuträglich, gerade in mobiler ansicht.

**Comment by Neolyum** [comment]
Distributors Done

**Comment by Nawatix** [comment]
Gibt die Buttons jetzt auch für die Buchung.
