### ISSUE TITLE
Buchungsdetails nicht über Titel verlinkt

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#64]
Die Buchungsdetails erreicht man nur beim klicken auf das Poster.
Alle anderen Detailseiten (von Filmen, Veranstaltungen etc) sind über einen Link auf dem Titel bzw das gesamte div zu erreichen.

Dieses verhalten bitte auch bei den Buchungen einbauen.

**Comment by Nawatix** [comment]
Ist gefixt, kommt mit dem nächsten update
