### ISSUE TITLE
sudo auf der Test VM

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#65]
wie im Chat von angefragt hat die Gruppe nun sudo auf dem Test System.

Dokumentiert hier **alle** Änderungen die ihr vornehmt, damit wir diese nachvollziehen können und im zweifel auf dem Produktivsystem nach stellen können.

**Comment by aendeavor** [comment]
Was passiert ist:

* Docker war kurzzeitig zum Testen drauf, ist dann samt MySQL und MariaDB runtergeschmissen worden (was notwendig war)
* MariaDB und MySQL wurden neu aufgesetzt

Ist es dokumntiert? **Natürlich**

Wenn Ihr auf der VM seid, und der neuste Stand wird gezogen, gibt es eine Datei namens `INSTALL.md`, in der ungefähr  steht, was noch passiert ist. Diese sollte auch auf _SonarQube_ zu finden sein.

**Comment by aendeavor** [comment]
Die Passwörter sind wieder die alten (for convenience)

**Comment by Oliver3911** [comment]
musste den Dienst gerade per Hand starten und habe gesehen das im cron script die Teile für den autostart auskommentiert sind. Bleibt das die nächsten Tage so?
Wäre gut zu wissen, wenn man die aktuelle Version haben will, das man die von Hand starten muss.

**Comment by aendeavor** [comment]
Entschuldige die lange Antwortzeit @COeins . Ich habe das übersehen. Es ist mit Absicht auskommentiert, und die aktuelle Version ist von Hand zu starten.

**Comment by aendeavor** [comment]
Nun werden wir nicht mehr viel machen - das Projekt neigt sich dem Ende. Deswegen wird dieser Issue geschlossen, damit man am Ende eine Übersicht hat.
