### ISSUE TITLE
PDF Unterschriften Feld zu klein

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#66]
noch eine kleine Anpassung für das Rechnungs-PDF
Die Felder für Datum und Unterschrift wirken schon arg klein.

Bitte hier einfach etwas mehr Platz schaffen. Gerade beim Unterschriftenfeld gerne viel Platz schaffen ^^

**Comment by Neolyum** [comment]
im nächsten Merge drin!
