### ISSUE TITLE
Beschreibungen bei Film- bzw Sonderveranstaltungen

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#67]
- [x] Die Vorschau bei Film- bzw Sonderveranstalltungs-Beschreibungen zeigt eingegebene Absätze nicht an. Ebenfalls wäre es schön wen diese rechtsbündig ist

- [x] Werden diese gespeichert?

- [x] Gibt die API diese zurück?

- [x] Eingabefeld Beschreibungen beim erstellen von Sonderveranstaltungen bitte wie das Feld bei Filmen

**Comment by paul-mars** [comment]
Auf Master haben die Sonderveranstaltungen nun das gleiche Feld wie die Filme.

**Comment by paul-mars** [comment]
Und ja die Absätze werden gespeichert. Ich würde schätzen das auch die API diese zurück gibt, sie werden jedoch von html einfach ignoriert. 
Das kann man zum Beispiel sehen, wenn man eine Beschreibung mit Absätzen bearbeitet.

**Comment by paul-mars** [comment]
@FelixRTU könntest du dass mit der API bestätigen?

**Comment by FelixRTU** [comment]
An die Beschreibung habe ich ehrlich gesagt nicht gedacht. Ist jetzt aber hinzugefügt (auf development)

**Comment by paul-mars** [comment]
@FelixRTU Und die wird auch mit allen Whitespaces weitergegeben oder?
