### ISSUE TITLE
Sonderveranstaltungen nicht löschbar

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#68]
Weder Admin noch Orga können momentan eine Sonderveranstaltung löschen.

![image](https://user-images.githubusercontent.com/18573108/72612074-0137cd80-392c-11ea-94a7-ffe052b18a64.png)

**Comment by aendeavor** [comment]
Schaue ich mir nachher gleich an

**Comment by Neolyum** [comment]
Fixed! Im nächsten merge dabei
