### ISSUE TITLE
Normaler User darf Buchungen anlegen

### ISSUE THREAD

**Issue by Oliver3911** [kino-im-kasten/SWT2019#7]
Dies sollte er NICHT können.

**Comment by Nawatix** [comment]
Ein normaler User kann jetzt keine Buchung mehr erstellen. Wie sieht es mit dem Editieren, Stornieren und Abrechnen aus, momentan kann das alles ein normaler User, soll ich das auch ändern?

**Comment by Oliver3911** [comment]
@Nawatix nur abrechnen und eintragen in den dutyplan

**Comment by Oliver3911** [comment]
Optional: wäre es möglich hier die Hinzufügen Knöpfe auszublenden. Dann würde der User weniger oft durch versehentliches Klicken die Fehlermeldung bekommen.
![image](https://user-images.githubusercontent.com/18573108/72333472-1f979200-36bc-11ea-8476-ead920db9022.png)

**Comment by FelixRTU** [comment]
Knöpfe sind jetzt ausgeblendet.
