### ISSUE TITLE
Loginbutton hover movement 

### ISSUE THREAD

**Issue by glombart** [kino-im-kasten/SWT2019#9]
Wenn ich über den Loginbutton hover, bewegt sich alles darüber um ein paar Pixel nach oben (bzw nach unten wenn ich wieder weghover). 
Ich vermute das hängt mit dem Schatten um den Loginbutton zusammen?

Tested on Firefox 71 (64 bit) - Ubuntu 19.04

**Comment by Oliver3911** [comment]
Passiert auch in Chrome Version 79.0.3945.79

**Comment by paul-mars** [comment]
Es lag daran, dass der Login Button beim Hovern noch einen Rand von einem Pixel bekommen hat, wodurch alles um 2 Pixel nach oben geschoben wurde.

Auf development ist das Ganze gefixt
